version: "3.2"

services:
  api:
    container_name: api
    image: api:latest
    build:
      context: .
      dockerfile: ./dockerfiles/api.Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - task-manager-network
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./api
        target: /opt/api
      - /opt/api/node_modules
  socket:
    container_name: socket
    image: socket:latest
    build:
      context: .
      dockerfile: ./dockerfiles/socket.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - task-manager-network
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./socket
        target: /opt/socket
      - /opt/socket/node_modules
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - task-manager-network
    ports:
      - "3306:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task-manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - task-manager-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      CLOUDAMQP_URL: amqp://rabbitmq:5672
    healthcheck:
      test: rabbitmq-diagnostics ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - type: bind
        source: ./messager/data
        target: /var/lib/rabbitmq
      - type: bind
        source: ./messager/log
        target: /var/log/rabbitmq
networks:
  task-manager-network:
    driver: bridge
volumes:
  db: